In [14]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
from sklearn.preprocessing import LabelEncoder, LabelBinarizer, OneHotEncoder

In [2]:
df = pd.read_csv('Dataset_analyse.csv')

In [3]:
df

,title,year,director,country,duration,genre,first_day,first_week,first_weekend,hebdo_rank,total_spectator,copies,rating_press,rating_public,casting,budget,lang,visa,award
0,rien ne va plus,1997,claude chabrol,france,6300,thriller,238507.8,172230,124628.8,3,458125,234,3.24,3.0,"[""Michel Serrault"", ""Isabelle Huppert"", ""Franç...",131200000.0,"[""francais"", ""hongrois""]",90016,0
1,la fille sur le pont,1999,patrice leconte,france,5400,drame,34301.6,154881,238497.8,5,663390,198,3.40,3.6,"[""Vanessa Paradis"", ""Daniel Auteuil"", ""Claude ...",990000000.0,"[""francais""]",90876,1
2,grosse fatigue,1994,michel blanc,france,5220,comedie,189874.2,417021,933258.2,2,2015230,189,3.34,2.7,"[""Michel Blanc"", ""Philippe Noiret"", ""Marie-Ann...",129400000.0,"[""francais""]",82266,1
3,braveheart,1995,mel gibson,etatsunis,9900,aventure action,32990.8,355642,228501.8,3,1231534,302,2.60,4.2,"[""Mel Gibson"", ""Sophie Marceau"", ""Catherine Mc...",72000000.0,"[""anglais""]",88091,9
4,regarde les hommes tomber,1994,jacques audiard,france,6600,thriller,177731.4,39739,824721.4,10,218831,46,3.06,3.3,"[""Jean-Louis Trintignant"", ""Mathieu Kassovitz""...",48658000.0,"[""francais""]",84098,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2202,be happy,2008,mike leigh,grandebretagne,7080,comedie,18126.0,110442,90372.0,9,362884,128,3.90,2.7,"[""Sally Hawkins"", ""Alexis Zegerman"", ""Andrea R...",44600000.0,"[""anglais""]",121057,1
2203,m butterfly,1993,david cronenberg,etatsunis,6060,drame,170550.2,32351,436355.2,10,101680,44,3.70,3.6,"[""Jeremy Irons"", ""John Lone"", ""Barbara Sukowa""...",71262750.8,"[""anglais""]",-1,0
2204,petits freres,1999,jacques doillon,france,5520,drame,176222.8,51749,596706.6,14,176880,-1,3.90,2.7,"[""Stephanie Touly"", ""Iliès Sefraoui"", ""Mustaph...",182000000.0,"[""francais""]",-1,0
2205,cookies fortune,1999,robert altman,etatsunis,7080,comedie,274642.4,63249,723909.4,13,239473,-1,3.80,3.3,"[""Glenn Close"", ""Julianne Moore"", ""Liv Tyler"",...",207600000.0,"[""anglais""]",97081,0
2206,si loin si proche,1993,win wenders,allemagne,8100,drame,170550.2,45238,436355.2,9,174764,42,3.70,3.6,"[""Peter Falk"", ""Nastassja Kinski"", ""Bruno Ganz...",71262750.8,"[""anglais"", ""francais"", ""allemand""]",82032,0

In [6]:
x = df['country']
x

0               france
1               france
2               france
3            etatsunis
4               france
             ...
2202    grandebretagne
2203         etatsunis
2204            france
2205         etatsunis
2206         allemagne
Name: country, Length: 2207, dtype: object

In [11]:
encoder = LabelEncoder()
encoder.fit_transform(x)

array([11, 11, 11, ..., 11, 10,  0])